Use tag to determine if to flatten or not an embedded anonymous field
wI2L/fizz pull request #85
Opened 2022-07-20 14:44 UTC by vladshub

2022-08-18 17:30 UTC, wI2L requested changes
LGTM, I would just like a few changes to the tests. Thanks

2022-08-18 17:30 UTC, wI2L commented on openapi/generator_test.go
> +		*Q `json:"data"`
Could you please add another field that is an exported field of struct type, but that has no tag? To test that its fiels are then inlined.

2022-08-18 17:30 UTC, wI2L commented on openapi/generator_test.go
> +		*Q `json:"data"`
Also, could you keep the tag value to `Q` to match the current output, where each field is named by its type in the final spec.

2022-08-18 17:30 UTC, wI2L commented on testdata/schemas/X.json
> +        "data": {
s/data/Q

2022-08-28 11:56 UTC, vladshub commented
@wI2L thanks for the review, fixed the issues.

2022-09-06 09:10 UTC, merged

2022-09-07 16:09 UTC, vladshub commented
Thank you 👍